Added new files of for loop
allatelunts/homeworksJava pull request #4
Opened 2024-09-15 15:11 UTC by allatelunts

2024-09-17 17:23 UTC, David91 requested changes

2024-09-17 17:23 UTC, David91 commented on AllDigitsOfNumber.java
> +            divisor *= 10;
This might lead to unexpected values of `divisor` due to capability of `int` type

2024-09-17 17:23 UTC, David91 commented on ElementsAToB.java
> +            }
Start iteration from `a`

2024-09-19 11:56 UTC, allatelunts commented on ElementsAToB.java
> +            }
I changed and started iteration from a

2024-09-19 12:18 UTC, merged